# Site settings
title: Patrik Robert Gerber
email: patrik.r.gerber@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://PatrikGerber.github.io" # the base hostname & protocol for your site
github_username:  PatrikGerber

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 3
paginate_path: "/page-:num/"

# Build settings
markdown: kramdown

# Google Analytics
google_analytics: UA-142179739-1